Learning/Django/pizzeria/pizzas/urls.py
from django.urls import path
from . import views

app_name = 'pizzas'
urlpatterns = [
		#Home page
		path('', views.index, name='index'),
		
		#Show the pizzas available.
		path('pizzas/', views.pizzas, name='pizzas'),
		
		#Show a list of the toppings available to that specific pizza.
		path('toppings/<int:pizza_id>/', views.toppings, name='toppings'),
	]

Learning/Django/pizzeria/pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('', include('pizzas.urls')),
    path('admin/', admin.site.urls),
]

Learning/Django/pizzeria/pizzas/models.py
from django.db import models

# Create your models here.

class Pizza(models.Model):
	name = models.CharField(max_length=200)
	date_added = models.DateTimeField(auto_now_add=True)
	
	def __str__(self):
		return self.name
	
class Topping(models.Model):
	pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)
	
	class Meta:
		verbose_name_plural = 'toppings'
		
	def __str__(self):
		"""Return a string representation of the model."""
		string = self.text[:50]
		if len(self.text) > 50:
			return string + "..."
		return string

Learning/Django/pizzeria/pizzas/views.py
from django.shortcuts import render
from .models import Pizza, Topping

# Create your views here.
def index(request):
	"""The home page for the pizzeria project."""
	return render(request, 'pizzas/index.html')

def pizzas(request):
	#Show the webpage containing all available pizza orders.
	pizzas = Pizza.objects.order_by('date_added')
	context = {'pizzas': pizzas}
	return render(request, 'pizzas/pizzas.html', context)

def toppings(request, pizza_id):
	#Show a webpage that displays all the toppings asssociated with the pizza
	#selected.
	pizza = Pizza.objects.get(id=pizza_id)
	toppings = pizza.topping_set.order_by('-date_added')
	context = {'pizza':pizza, 'toppings':toppings}
	return render(request, 'pizzas/toppings.html', context)

Learning/Django/pizzeria/pizzas/templates/pizzas/base.html
<p>
  <a href="{% url 'pizzas:index' %}">Home</a> - 
  <a href="{% url 'pizzas:pizzas' %}">Pizzas</a>
</p>
{% block content %} {% endblock content %}

Learning/Django/pizzeria/pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}
{% block content %}
  <p>
    Hello World!
    Welcome to my pizzeria website.
  </p>
{% endblock content %}

Learning/Django/pizzeria/pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}

{% block content %}

  <p>Pizzas</p>
  
  <ul>
    {% for pizza in pizzas %}
      <li>
        <a href="{% url 'pizzas:toppings' pizza.id %}">{{ pizza }}</a>
      </li>
      {% empty %}
        <li>Sorry, no pizzas have been added yet.</li>
    {% endfor %}
  </ul>
  
{% endblock content %}

Learning/Django/pizzeria/pizzas/templates/pizzas/toppings.html
{% extends "pizzas/base.html" %}

{% block content %}
  
  <p>These are the toppings for {{ pizza }}</p>
  <ul>
    {% for topping in toppings %}
      <li>{{ topping }}</li>
    {% empty %}
      <li>Sorry there are no toppings for this pizza yet.</li>
    {% endfor %}
  </ul>
  
{% endblock content %}